### ISSUE TITLE
AUDPC is the same constant in summarise_trace

### ISSUE THREAD

**Issue by PaulMelloy** [IhsanKhaliq/ascotraceR#131]
Just noticed that `summarise_trace`  updates all entries (rows) with AUDPC instead of for each point in time. See vignette results.
Is this a bug, or am I not reading it correctly?

**Comment by adamhsparks** [comment]
Since I’ve only ever used whole seasons/locations I just left it at that not seeing the point of having it by day. If you can think of a reason we can do that.


--
Dr Adam Sparks | Senior Research Scientist
Farming Systems Innovation
Primary Industries Development
Department of Primary Industries and Regional Development
3 Baron-Hay Court, South Perth WA 6151
t +61 (0)8 9368 3689 | m +61 (0)415 489 422 | w dpird.wa.gov.au

**Comment by PaulMelloy** [comment]
I see your point about AUDPC not being useful by day.
But perhaps people might find it misleading in this table if whole season AUDPC on each line (day)?
IMO each line of the `summarise_trace` should detail the epidemic on that day (or in this case up to the day). It may not be useful, but I think it's more accurate.

**Comment by adamhsparks** [comment]
I can’t see any reason to have it by day as that’s not a AUDPC value that’s used and adds confusion. If you think it’s misleading then I’ve not properly documented the function. This is a summary of the model output. AUDPC is a summary of that output.

I only included it as a courtesy. It can be removed and users can calculate the value themselves if they want it.


--
Dr Adam Sparks | Senior Research Scientist
Farming Systems Innovation
Primary Industries Development
Department of Primary Industries and Regional Development
3 Baron-Hay Court, South Perth WA 6151
t +61 (0)8 9368 3689 | m +61 (0)415 489 422 | w dpird.wa.gov.au

**Comment by PaulMelloy** [comment]
Perhaps just update the documentation to state that it is AUDPC for the whole season instead of "daily time-step" then.

It is nice to have in there

**Comment by adamhsparks** [comment]
Closed https://github.com/IhsanKhaliq/ascotraceR/commit/d3443d92f19d8128564d72324ddc08c8947d42d5
