### ISSUE TITLE
'Rcpp_precious_remove' not provided by package 'Rcpp'”

### ISSUE THREAD

**Issue by PaulMelloy** [IhsanKhaliq/ascotraceR#152]
Submission to Phytopathology recommended the following change to the package by reviewer 2

> When I tried running the code on GitHub
> https://github.com/IhsanKhaliq/ascotraceR
> using the command format_weather, I got this error message below, and had to update Rcpp for the rest of the code to work. Perhaps add a message about this in case users have the same problem and don’t know the implications of the error message.
> “Error in C_force_tz(time, tz = tzone, roll) : 
>  function 'Rcpp_precious_remove' not provided by package 'Rcpp'”

Perhaps adding `Rcpp` to the `imports` or `suggests`  in the `DESCRIPTION` file with a minimum version?
Do you think this would amend this for future users @adamhsparks

**Comment by adamhsparks** [comment]
If _Rcpp_ were an import of our package, CRAN would not have allowed it to be published without listing it as such. You cannot just put it in Imports or Suggests because it is not imported by this package unless you jump through some hoops. 

This isn't a bug in _ascotraceR_. My best guess is that it's somewhere upstream with a package that _ascotraceR_ calls, which uses _Rcpp_.

**Comment by PaulMelloy** [comment]
Yes, this issue has arisen from a `lubridate` function `force_tz().
I agree, I am not labelling it as a bug, just documenting it.
Perhaps we label it as `won't fix`

**Comment by adamhsparks** [comment]
Put a note in the README about reinstalling _Rcpp_ until _lubridate_ fixes the bug I reckon.

**Comment by adamhsparks** [comment]
Closed with https://github.com/IhsanKhaliq/ascotraceR/commit/b6a582704c6415d9012519ceef576bf689e20cd1
